# Generated by Django 2.2.7 on 2022-08-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220831_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uid',
            new_name='id',
        ),
    ]
