# Generated by Django 2.2.7 on 2022-09-01 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
