# Generated by Django 2.2.7 on 2022-09-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20220901_0045'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
